### PR TITLE
Flake8 fixes 

### LINKED ISSUE #16: flake8 opportunities
Many flake8 fixes needed.

### PR DESCRIPTION
**Pull request by sourabhaa**
Fixes #16.

### CODE REVIEW

**Review by srevinsaju — CHANGES_REQUESTED** [review]
A rebase would be nice

**Comment by sourabhaa** [comment]
The branch is up to date. I'm not sure why the previous commits to master branch showed up. This also happened in #20. Any suggestions to resolve?

**Comment by sourabhaa** [comment]
Since the branch is up to date with the master, I think squash and merge would work fine.

**Comment by chimosky** [comment]
> The branch is up to date. I'm not sure why the previous commits to master branch showed up. This also happened in #20. Any suggestions to resolve?

Sure, an interactive rebase dropping both commits would do the trick. Already mentioned this in #20.
Also drop the merge commit ba39ea4 as it makes it difficult to view the diff when using a diff tool.

> Since the branch is up to date with the master, I think squash and merge would work fine.

Can you squash the commits and push here? Let me know if you need any help.

**Comment by sourabhaa** [comment]
> Can you squash the commits and push here? Let me know if you need any help.

Done as you suggested. @chimosky kindly review.

**Comment by chimosky** [comment]
Reviewed, thanks. Merged by hand as bd72848.

Some comments; 

Some of the imports can occupy the same line, if you want to ignore some errors you can add them to `.flake8` in the format
```
[flake8]
ignore = F405
```

You can search our repos for these files and you'll see others.

**Pull request closed without merging**
