### PR TITLE
Feature : Add Accuracy Percentage Display

### PR DESCRIPTION
**Pull request by ghost**
* Implement Accuracy % display ingame & game-over screen.

Screenshot 2024-04-19 at 4 49 01 PM
Screenshot 2024-04-19 at 4 49 12 PM

Kindly review @walterbender @chimosky @quozl .
Thanks.

### CODE REVIEW

**Comment by chimosky** [comment]
I don't see a reason why we'll need to show the accuracy of each game, why do you think we need it?

**Comment by ghost** [comment]
- To ensure you don't just press random numbers and still get the correct answers, especially at medium and hard levels, where there are more questions, accuracy should be monitored.
- It's possible to score high with poor accuracy due to random guessing, or to have high accuracy with low points because of slower responses.
- The game emphasizes both speed and accuracy, as they are closely linked. Achieving a balance between the two is crucial for success.

**Comment by chimosky** [comment]
> * To ensure you don't just press random numbers and still get the correct answers, especially at medium and hard levels, where there are more questions, accuracy should be monitored.
 

Pressing random numbers and getting correct answers is normal, the odds of being right depends on the number of options you get and the frequency of being right isn't that high, I don't see how that's a reason we should show accuracy.

>     * It's possible to score high with poor accuracy due to random guessing, or to have high accuracy with low points because of slower responses.


I don't see how this is a valid reason to show accuracy.

>     * The game emphasizes both speed and accuracy, as they are closely linked. Achieving a balance between the two is crucial for success.

Could you tell me how showing the accuracy would achieve a balance between speed and accuracy?

**Comment by ghost** [comment]
Yes, if pressing random button and getting correct is accepted as a part of game, then this might not be great addition, thanks.

**Pull request closed without merging**
