### PR TITLE
Fix several flake8 warnings & Update .flake8

### LINKED ISSUE #16: flake8 opportunities
Many flake8 fixes needed.

### PR DESCRIPTION
**Pull request by ghost**
This closes https://github.com/sugarlabs/jamath-activity/issues/16.
- Updated .flake8 with latest pep8 guidelines regarding operator break.
- Fixed all the flake8.

Kindly review @walterbender @chimosky @quozl .

### CODE REVIEW

**Comment by chimosky** [comment]
Running flake8 shows `./juego.py:404:17: F821 undefined name 'game_over'` and rightly so as `game_over` exists in `play` so you'll have to change that.

**Comment by ghost** [comment]
Changed that!
Thanks

**Comment by chimosky** [comment]
Tested 98f44a4, it'll be great to not change the position of `game_over` and just change the indentation.

With your change, the activity starts and after the play button is clicked, the activity canvas still shows the same screen and the sound plays to tell you the game has started and after a number of failures you see the game over screen.

Nothing in the log show clearly why, but the log shows this;
```python3
1714811501.291445 ERROR root: Key AudioPrev unrecognized
1714811501.398156 ERROR root: Key AudioPrev unrecognized
1714811501.688593 ERROR root: Key AudioPlay unrecognized
1714811501.788952 ERROR root: Key AudioPlay unrecognized
```

**Comment by ghost** [comment]
Yes, its generating errors.

**Pull request closed without merging**
