### PR TITLE
UI Enhancement

### PR DESCRIPTION
**Pull request by sourabhaa**
1. Removed displaying lose/win which seemed discouraging. @quozl @chimosky please share your thoughts.
In game over page, comparing the current score with the high score, a text would be rendered saying 'You win' or 'You lose'. I think showing the win/lose would be discouraging to a kid. Instead, just the score and high score could be displayed.
Current game over UI:
cur_gameover_jamath

proposed game over UI:
jamath_gameover_new

2.  Improved game page UI; relocated question to the top-centre of the screen for better visibility; added padding to score, high score, question and timer.
Current UI:
current_UI_jamath

Proposed UI:
jamath_UI_updated

@quozl @chimosky @srevinsaju  kindly review.

### CODE REVIEW

**Comment by quozl** [comment]
I'm not familiar with the activity.  Your patches don't follow our guidelines on commit description contents.  I was unable to see how the UI is improved or how you did it.

**Comment by sourabhaa** [comment]
> I'm not familiar with the activity. Your patches don't follow our guidelines on commit description contents. I was unable to see how the UI is improved or how you did it.

Sorry @quozl , I've updated the description.

**Comment by quozl** [comment]
Thanks.  Looks good.

**Comment by chimosky** [comment]
> I'm not familiar with the activity. Your patches don't follow our guidelines on commit description contents. I was unable to see how the UI is improved or how you did it.

I agree with quozl on this, your commit messages in this scenario need to be more than one liners as not everyone knows how your change improves the UI except you tell them.

**Comment by sourabhaa** [comment]
> > I'm not familiar with the activity. Your patches don't follow our guidelines on commit description contents. I was unable to see how the UI is improved or how you did it.
> 
> I agree with quozl on this, your commit messages in this scenario need to be more than one liners as not everyone knows how your change improves the UI except you tell them.

Thanks @chimosky, I've updated the commit messages.

**Comment by quozl** [comment]
Your new commit messages are better, but they could be better still.  https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits has a list of items to consider in writing commit messages.  Look for things you have said in the pull request comments as conceptual candidates for adding to the commit messages.  Commit messages usually don't include images though.

**Comment by sourabhaa** [comment]
Thanks @quozl , I've updated the commit message with better explanation :)

**Comment by chimosky** [comment]
Your new commit messages are better and way more helpful, I'll wait for quozl's review.

**Comment by quozl** [comment]
Thanks, looks fine.

**Pull request merged**
